[package]
name = "hygiene_mnwe"
version = "0.1.0"
edition = "2021"

[features]
default = ["original"]
original = []
wrapper = []

[dependencies]
indirection = { version = "0.1.0", path = "indirection" }
